### ISSUE TITLE
Local installation on docker problem

### ISSUE THREAD

**Issue by perplesso82** [TabbycatDebate/tabbycat#2203] opened 2022-12-19 17:22 UTC
I'm trying to install tabbycat using docker on a Windows 11.
The installation was ok, but at web-1 startup an error message says:
nginx.1 | nginx: [emerg] invalid number of arguments in "worker_processes" directive in ././config/nginx.conf:8
3 other containers are correctly runnning: worker-1 db-1 redis-1

OS: Windows 11 home 22H2 build 22621.963
Tabbycat 2.7.4 (zip file)
Docker 4.15.0 with WSL 2
![error](https://user-images.githubusercontent.com/78228926/208483205-0262a0a8-96aa-4a18-839f-72e41178806a.png)

CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
RAM: 16GB

**Comment by philipbelesky** [comment] 2022-12-24 00:06
Hey, thanks for reporting this, I can reproduce it on my end and will hopefully have it fixed up soon.

**Comment by maclask** [comment] 2023-01-13 16:56
Hi, I have encountered the same problem. 
It is caused by lack of some environmental variables declaration in docker-compose.yml

The quick solution is to edit /config/nginx.conf and hard-code values instead of referring to environmental vars.

**Comment by FaizAlam** [comment] 2023-04-16 09:23
> Hi, I have encountered the same problem. It is caused by lack of some environmental variables declaration in docker-compose.yml
> 
> The quick solution is to edit /config/nginx.conf and hard-code values instead of referring to environmental vars.

I tried hard-coding the values instead of env vars, but still it produces the same error.

**Comment by maclask** [comment] 2023-04-16 14:15
> > Hi, I have encountered the same problem. It is caused by lack of some environmental variables declaration in docker-compose.yml
> > The quick solution is to edit /config/nginx.conf and hard-code values instead of referring to environmental vars.
> 
> I tried hard-coding the values instead of env vars, but still it produces the same error.

Try to edit mentioned file and remove references to enviromantal vars. I have forked this repo so you can check it on my github

**Comment by odinakholiqov** [comment] 2023-04-21 13:48
Hey there,
I'm trying to install tabbycat using docker on Windows 11 too. I hard-coded `NGINX_WORKERS to 4 and NGINX_WORKER_CONNECTIONS to 1024`, but the problem did not get solved.

Now I am stacked here. Could you please let me know where is the problem?

![Screenshot 2023-04-21 184705](https://user-images.githubusercontent.com/113301533/233652782-46c4628d-947f-47b1-bf78-481fc908f666.png)

**Comment by FaizAlam** [comment] 2023-04-21 14:51
Hey @odinakholiqov I faced the same problem but then I cloned @maclask 's ergotab and followed the same procedure to "install on heroku" and it worked fine for me.

**Comment by odinakholiqov** [comment] 2023-04-21 14:59
@FaizAlam thank you bro! Could you please explain to me how to do the "install on heroku"?
I actually want to run it in my Docker.

**Comment by tienne-B** [comment] 2024-06-20 23:45
Fixed in b3d4c6154fc74e79c0d2167be48a73df94f6ed5d

**Closed by tienne-B** 2024-06-20 23:45 UTC
