### ISSUE TITLE
Anonymized speakers are revealed in the public record page

### ISSUE THREAD

**Issue by inohan** [TabbycatDebate/tabbycat#2497] opened 2024-09-08 11:59 UTC
When the public record page of teams with anonymized/redacted speakers are accessed, the speaker name is revealed in the `About (Team Name)` section instead of showing up as *Redacted*.
In the image below, Speaker 1A is set to an anonymous/redacted speaker, but the name is revealed.
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/a98b9b3b-d776-477c-a475-11ec0d5f9c37">

This also applies for when ballots are released to public.

**Comment by tienne-B** [comment] 2024-09-11 17:55
Closed as a duplicate of #2249 .

**Closed by tienne-B** 2024-09-11 17:55 UTC
