### ISSUE TITLE
Lock debate importances when sorted by importance

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1449] opened 2020-05-03 18:23 UTC
The concern is that when the adjudicator allocation view is sorted by importance, and the importance of a debate changes, its position suddenly changes and using the sliders may glitch due to the correspondance with the moving object. Thus, an indication of the sorting with locking could prevent confusion if importances change.

**Comment by philipbelesky** [comment] 2020-05-04 00:25
Hmm, rather than add another state or magic behaviour to the sorting, what if we just changed the sort function so that it does a one-off sort rather than updating the list? I don't think there's really any circumstance where you want the debates to be reordering themselves live.

**Comment by tienne-B** [comment] 2020-05-04 00:33
Sounds good!

**Comment by philipbelesky** [comment] 2020-05-09 01:56
Closing as this has ended up as a duplicate of #1275

**Closed by philipbelesky** 2020-05-09 01:56 UTC
Labels: admin ui, enhancement

**Comment by tienne-B** [comment] 2020-05-09 01:57
Good catch; forgot that one!
