### ISSUE TITLE
Feedback by source, when clicked at the hyperlink redirects to another adjudicator

### ISSUE THREAD

**Issue by mpopst** [TabbycatDebate/tabbycat#1244] opened 2019-09-19 03:45 UTC
![image](https://user-images.githubusercontent.com/30660789/65211848-7aa2da80-da76-11e9-9b61-f859b4c4adcb.png)
When you click at the link in feedbacks, the link redirects to another adjudicator.

**Comment by philipbelesky** [comment] 2019-09-19 12:10
Hey @mpost, thanks for reporting this issue. I've had a quick look on this on my end and it seems to be working. Could you describe what the expected behaviour is here, and what it is you see?

When viewing feedback by target, the "X feedbacks" link shows you feedback *about* that adjudicator. When viewing feedback by source, the "X feedbacks" link shows you feedback *by* that adjudicator or teams; i.e. the feedback they have submitted  about other people. Does that match what you expected and what the link redirects you to?

**Comment by mpopst** [comment] 2019-09-21 06:52
When I click on *5 feedbacks* for the adjudicator John Smith, it opens the feedback page for the adjudicator Sarah Jane. When you pass the mouse one their names, on the left of the table, it works fine. Here a print from a tournament I tabbed some months ago:
![image](https://user-images.githubusercontent.com/30660789/65369349-305e5c80-dc22-11e9-89db-9b32fe42b4c9.png)

When I pass the mouse on the number of feedbacks of mine, it says it will redirect to the adjudicator target with id 5. But on this screen, it says I have id 8, when I pass the mouse:

![image](https://user-images.githubusercontent.com/30660789/65369379-9b0f9800-dc22-11e9-8932-cbe26a3d5ad0.png)

In fact, the *view Matheus's record* is the one correct. You can see it on the URL bar in the print bellow.

![image](https://user-images.githubusercontent.com/30660789/65369411-df029d00-dc22-11e9-8177-433399d3564a.png)

The behavior I was expecting that both were redirecting to the same place.

**Comment by philipbelesky** [comment] 2019-09-21 08:39
Ah, thanks for clarifying, those IDs should definitely be consistent between the two links. I've tried to replicate this across `2.2.10` and `2.3.0` branches on a few instances without any success. Did this only crop up with this tournament, or have you noticed it across different tournaments/sites?

If you were ok with adding me as a collaborator to the heroku instance I could have a look at your particular dataset. Alternately we could try upgrading the instance to see if that would resolve it.

**Comment by tienne-B** [comment] 2019-09-21 18:37
Might have been fixed with dc3f207bab.

**Comment by mpopst** [comment] 2019-09-22 01:49
Please, send an email to ma.popst@hotmail.com

**Comment by philipbelesky** [comment] 2019-09-28 04:18
I think @tienne-B was right regarding the fix; either was its definitely resolved as per the latest release. Thanks again for the report and your help debugging @mpopst!

**Closed by philipbelesky** 2019-09-28 04:18 UTC
