### ISSUE TITLE
Emojis still visible on Team Standings page

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#833] opened 2018-09-24 14:15 UTC
Minor bug report. This may be intentional to save space, but on the Admin facing team standings page, opponent teams are still shown with emojis as opposed to showing team name when use of emojis has been disabled. (v2.1.2)

![image](https://user-images.githubusercontent.com/3196468/45957299-d061c400-c068-11e8-9e89-1c380ad8052b.png)

Public team standing page shown below. Note this is with R4 silent so data is not quite the same.

![image](https://user-images.githubusercontent.com/3196468/45957332-e079a380-c068-11e8-8d5c-7ffb9c5df2ff.png)

**Comment by philipbelesky** [comment] 2018-09-25 00:27
Hey thanks for the report. This is the intended behaviour as using full names makes the horizontal spacing very large and unwieldy in tournaments with 6+ rounds. That said it should probably be consistent with the public version of the page and having a super wide table isn't a huge problem on admin pages given they are overwhelming used on the desktop. I'll have a play and see if switching to names works.

**Comment by tienne-B** [comment] 2018-09-25 02:11
It actually seems to be consistent with the public version of the page. Check the "Team Tab" public page (it is the equivalent to admin's Team Standings). This bug more aptly shows that the page titles are inconsistent between tabroom/public views. I also somewhat remember an admin equivalent of the public standings page, but I can't specifically remember it.

**Comment by czlee** [comment] 2018-10-04 05:15
Yeah, what @tienne-B said—the "Current Team Standings" page isn't the equivalent of the Team Standings page in the admin area.

The page titles being inconsistent is also by design. "Standings" is the generic name (well, it's actually a hangover from the name given to it in 2010), whereas I normally think of the "Team Tab" as being the summary released after the tournament. Since the public view of (complete) team standings is released only after the tournament, we override the title to "Team Tab". (And similarly for all other standings page.)

**Comment by philipbelesky** [comment] 2018-10-28 02:46
I think there was no action required here so closing this issue. Feel free to reopen if I've missed something.

**Closed by philipbelesky** 2018-10-28 02:46 UTC
