### ISSUE TITLE
Email notifications don't check/warn when variables are missing

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1054] opened 2019-03-18 12:17 UTC
2.3.0A

When sending email notifications where a variable doesn't exist, like {{ URL }} there are no warnings/checks and as such the variable is sent as blank on the email.

I have primarily been encountering this issue when adding an adjudicator after the private URLs have been initially generated and forgetting to generate new private URLs for the users.

I have only tested this with {{ URL }} on the Email Participants Adjudicator Assignment page, but I have assumed this happens with other variables as well. 

I am not sure what the preferred way of checking/warning is and whether you would still want the emailed to be sent if it is missing variables.

**Comment by tienne-B** [comment] 2019-04-24 21:22
Duplicate of #802.

**Closed by tienne-B** 2019-04-24 21:22 UTC
