### ISSUE TITLE
Justification bars for speaks

### ISSUE THREAD

**Issue by nathanielyoon** [TabbycatDebate/tabbycat#2166] opened 2022-11-19 02:24 UTC
In APDA, judges can only give speaks outside a certain range (usually 35 and above, 15 and below) if they confirm them with tab first. This usually involves a quick chat with the tournament director or observer who hears out why the judge thinks the speech was exceptional enough to warrant such a high score. If this justification is accepted, tab can manually enter the higher speaks, but if it's not (or there is no justification submitted), the speaks should be limited to that bound.

**Comment by philipbelesky** [comment] 2022-11-19 03:51
Would the tab person who enters this data usually be a tab director/admin (eg good tabbycat knowledge) or would it also need to be entered by assistants? (eg novice users just doing data entry)

I ask as there's definitely a spectrum of ways to manually enter a super high/low score, such as using the Edit Database area. But it sounds like we may also want a more user/UI facing way to perform that action. Some rough ideas:

- Having a seperate set of score min/max settings for admin users as compared to assistant users
- Having an 'override' checkbox or similar shown to admin users that unlocks the score fields in the UI
- ...?

I think the somewhat tricky part is that I assume these overrides would need to be able to be tracked and confirmed like 'normal' ballot data where there is a clear chain of custody / history / verification.

**Comment by nathanielyoon** [comment] 2022-11-21 16:59
It'd usually be one of the tournament directors, so only a couple admin users would need this feature. Additionally, ADPA tournaments often have a "tab observer," someone who's older, sometimes graduated, who advises and reviews the process, and is often consulted when judges want to justify a speaker score.

The issue has less to do with editing scores afterwards (especially cause 35+ speeches are extremely rare, and 15- scores are even rarer), but with making sure that judges don't enter a score outside the 16-34 range on their own. Unlike BP (and other formats I assume, I've just never done them), novices and even first-time judges frequently chair rounds, and the closest thing to a judging manual is a slightly out-of-date speaker scale that almost nobody follows. So without some kind of barrier, I can see less experienced judges inputting a 36 for a pretty good speech, and this might cause delays or inaccurate placements (e.g. which is fairer, editing down to the maximum un-justified score of 34, or briefly informing the judge of rules/scale and having them re-assign speaks?). 

I think the first suggestion of distinct score min/max settings is good, but not between admins/assistants, just between admins/judges entering ballots. (I also am not that experienced with this software, perhaps this is already available?)

**Comment by czlee** [comment] 2022-11-22 11:18
To throw in another idea, would the following workflow work:
1. Judges can enter any score, including scores outside the no-justification range
2. If a judge enters a score outside the no-justification range, they're shown a message asking them to visit the tab room to justify the score
3. The score is flagged, _but not adjusted_. That is, the desired score is entered into the database. But the tab team sees something on the results screen, as well as a warning message, warning them that an out-of-range score hasn't yet been marked as justified. Of course the tab team can edit the score as usual if they desire.
4. It's on the tab team to decline to complete the round until all unjustified out-of-range scores have had their flags cleared.

I thought the data model might be a little simpler this way:
- add "require justification at" scores to preferences; if blank, justifications are never required
- add a boolean field to SpeakerScoreByAdj or SpeakerScore (I forget whether APDA is consensus ballots, sorry)
- add logic that automatically changes that boolean field to true if the score is out of no-justification range (but within the hard limit range)—this way the original desired score isn't lost at the beginning
- add logic flashes big warning messages at tab teams if they try to complete the round while there are still flagged scores

(I used to judge at the APDA tournament hosted by my campus, but since I didn't have an APDA background that was the sum total of my interaction with APDA.)

**Comment by tienne-B** [comment] 2022-11-22 12:36
Would it actually be necessary to make any data model changes for this? The preference value(s) could merely be used within the templates to highlight those scores rather than to set a "flagged" column which is then picked up.

**Comment by philipbelesky** [comment] 2022-11-22 12:58
Yea, that would be my thought as well. Trying to model the nuances of this in data and UI seems tricky and potentially more error prone given differences across formats. Using the templates and the existing capacity to add notes (or just relying on briefings) seems smoother.

**Comment by tienne-B** [comment] 2023-09-04 20:54
I'm revisiting this task and think implementing this would incur much more overhead than if handled through briefings and diligent tabbing.

**Closed by tienne-B** 2023-09-04 20:54 UTC
