### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by MELCHI-TABBER1** [TabbycatDebate/tabbycat#1846] opened 2021-07-18 16:40 UTC
I hit an internal server error while trying to load this URL:
https://gyabaahtabz.herokuapp.com/uccinterhalls21/admin/draw/round/5/

Please describe what you were doing when the error happened, along with any other useful information:
I generated a draw for this round but did not change from power pairing to random however, I edited the sides and match but did not realize that after editing, some teams were in more than one room and proceeded, only to see an internal server error.

**Comment by tienne-B** [comment] 2021-07-18 17:06
Sorry to close again, but this is a duplicate of #1845. Thanks for giving more details; it matches up with the comment on the number of teams on FB. My suggestion is to upgrade ([instructions](https://tabbycat.readthedocs.io/en/stable/install/heroku.html#upgrading-an-existing-heroku-app)) to the latest version, as 2.2.10 is 2 years out of date.

**Closed by tienne-B** 2021-07-18 17:06 UTC
