### ISSUE TITLE
Venues not sorting by score/priority

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1458] opened 2020-05-14 21:37 UTC
Hi all, apologies for another very minor GitHub issue (I swear I am not intentionally hunting for issues).

In the venue allocation window, the venues do not appear to be sorted by score. In my case, I think they're being ordered by the reverse order of when they were added (i.e. #29 was the last venue I added in my most recent import of venues).

My guess is this was ported over from the adjudicator allocation window so "score" doesn't exist as a concept. The window should sort by venue priority and "sort by score" should be renamed "sort by priority"

![image](https://user-images.githubusercontent.com/3196468/81988288-4d530e80-968f-11ea-85a5-4617549add1b.png)

**Comment by tienne-B** [comment] 2020-05-14 21:56
Yeah, Philip and I are working on improving the venue allocation views; they are sorely lacking. Good find though! (Wouldn't matter much for online tournaments, but the red highlight for constraints do not work either...)

Keep your GitHub issues coming! I'm disappointed you _aren't_ hunting for issues; we need them! The experience of using software is based on the attention to detail and the expectations of its users. I know that for myself, my frame is quite wide and I'd probably miss a lot of these potential improvements and fixes!

**Comment by czlee** [comment] 2020-05-31 05:23
Yeah, ditto what @tienne-B said. There's no way for us to keep tabs on everything, so it's fantastic that you're bringing these to our attention now. We might on occasion explain why we won't fix one or why one's by design or whatever, but that doesn't mean we appreciate the communication channel any less 😊

**Comment by tienne-B** [comment] 2022-12-14 02:04
Fixed in 0d007e68176dcfe6d5ecaa3f5013583b44305917

**Closed by tienne-B** 2022-12-14 02:04 UTC
