### ISSUE TITLE
Rework/Fix Ballot Check-In's handling of venue names

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#363] opened 2016-08-11 07:18 UTC
Currently `get_debate_from_ballot_checkin_request` throws an error if two venues have the same name given it uses `Venue.objects.get(name__iexact=v)` and returns a single venue. It's probably not desirable to enforce venue name uniqueness nor is it a good idea to have ballot checkins done by searching for exact strings given the use of VenueGroup prefixes and the chance ballots may not have accurate names. 

Possible solution:
- Switch to using a select dropdown; possibly something [fancy like this](#348 I’m waiting to hear back on, although it seems to definitely be correct for the non senior levels)
- If so ensure that this is auto-focused on page load for fast identification

Related error:

```
Internal Server Error: /t/tw206/admin/results/round/1/checkin/detail/

MultipleObjectsReturned at /t/tw206/admin/results/round/1/checkin/detail/
get() returned more than one Venue -- it returned 2!
```

**Comment by czlee** [comment] 2016-08-11 22:40
Are there any elements that primarily look like textboxes but have automatic partial-match menus that descend from the textbox? So basically something functionally the same, except that it nudges the user to type rather than click-and-scroll?

**Comment by philipbelesky** [comment] 2016-08-12 01:32
That might be possible using the `list` attribute of an input element otherwise the [live search](https://silviomoreto.github.io/bootstrap-select/examples/#live-search) element (incorrectly linked in the first post) does a pretty good job of prompting users to type.

**Comment by czlee** [comment] 2016-09-03 20:36
An effect of this change was to render each of these error messages obsolete:

- "There wasn't a debate in venue 'XYZ' in this round."
- "The ballot for venue 'XYZ' has already been checked in."

In ordinary use, these never happen, because the front-end doesn't allow them to be selected in the first place. Is this okay with you? I had them originally in there to catch things like adjudicators writing down their venue names incorrectly (or switching rooms and writing down the new room locations), so that runners wouldn't be confused when there was an unspecified "error retrieving information for the debate". Now that pre-printed ballots are becoming the norm this is probably less of a problem.

We would still need server-side checks in case, _e.g._, someone changes a venue/status of a debate, causing the information loaded on to the ballot check-in page to be out-of-sync with the database. But this is the sort of failure where I think it's easiest and acceptable just to handle gracefully (_i.e._, throw a 400 and let jQuery pick up on it with "Please try reloading the page"), rather than provide a strictly informative error message about exactly why it's not working.

Other options:

1. Include all venues in the dropdown always rather than filtering them for just those venues with debates and that haven't already been checked in. But I think that's a worse option.
2. If the venue string entered isn't in the dropdown, have the client send the user-provided string to the server instead and retrieve a useful error message (or the debate).

**Comment by czlee** [comment] 2016-09-03 20:41
Actually, it would be nice to have "The ballot for venue XYZ has already been checked in" still there—preprinted ballots don't remove that circumstance. This would require the client to remember which venues had already been entered though (and the server to send through which ballots had been checked in before page load).

Also come to think of it, the assumption that changes to check-in status won't happen other than at a single client terminal is probably a bad one: it makes it impractical to have two ballot check-in stations running simultaneously.

Is there a way to have all the venues listed for ID lookup, but hide the ones without debates/already checked in from the visible dropdown?

**Comment by philipbelesky** [comment] 2016-09-04 00:16
The frontend list-option filtering isn't a strict limit — on some browsers it is possible to enter arbitrary text irrc.

I think if you hid the option elements they would not be available on lookup, or the same iteration could be used elsewhere to create the list. 

Another option (to enable multi terminal use) would be to have each lookup/save action bring down a list of currently-not-checked in ballots so that the list is always current. 

Either way the code and backend methods for this are a bit messy, I think any changes to this form and its handling should be done in Vue (although if you want to fix it otherwise feel free to assign yourself). Checkin doesn't seem that popular so I'm removing from the Foldex milestone too.

**Comment by czlee** [comment] 2016-09-04 00:31
It's possible to enter arbitrary text; the problem is rather that because the client looks up the venue ID from the list, it doesn't know what to send to the server when you do enter arbitrary text. Currently, it attempts a lookup which fails, then it displays a generic error message. For venues that don't exist this is fine. But it can't distinguish between these and venues that do exist but have some other problem (no debate or already checked in), so it displays the same error message for both.

If we wanted to be fancy, we could list all venues, but list those that don't have a debate or are already checked in in red, and sort entries so that "valid" venues appear at the top of the list :wink: (Is this actually possible? If it's not too much effort it might be worth a go.)

That said, at the point where each save action updates the entire list, we may as well have the client actually query the server for the _current_ ballot check-in state of the requested venue too. The more I think about it, regardless of what the client does to help the user along, when the client retrieves details and posts check-ins, for every existent venue I think it should always retrieve info from the server, _i.e._ it should not short-circuit an AJAX request unless the venue doesn't exist at all.

If you want to rework things to Vue first, I can wait (or maybe I'll start learning Vue). I was just reworking the ballot views into class-based views and noticed a bunch of code that used to catch typical errors that's now mostly redundant, and wanted to find a proper solution.

**Comment by philipbelesky** [comment] 2016-09-04 09:12
Hmm not sure if the listing with colours thing is possible with standard form elements, but at worst a (checked in) could be added to the label. 

The other option would be to rethink the UI entirely; perhaps have a bunch of buttons (one for each venue, perhaps grouped by venue group) that show checked-in state, and when clicked bring up the standard checkin form. The list could be dynamically filtered by a search box to keep the existing keyboard centric flow. 

If you wanted to learn Vue the could be a good place to start, even if its just a detached mockup of the UI (I'd be happy to style it and wire it into the template if needed).

**Comment by czlee** [comment] 2016-09-04 20:13
Yeah, I started looking at Vue, it looked intimidating :open_mouth: I might give it a go, but probably not soon.

(I don't really have thoughts on rethinking the UI… unless there might be too many buttons, but I'm guessing there's a solution to that.)

**Comment by tienne-B** [comment] 2019-09-20 21:18
Closing as this task seems obsolete. Ballot check-ins are now handled like other checkins, and the identifier of debates do not include venue names.

**Closed by tienne-B** 2019-09-20 21:18 UTC
Labels: admin ui, bugs, low priority
